sudo: false
language: ruby
rvm:
  - 2.4.1
services: mysql
before_install: gem install bundler -v 1.16.1
notifications: false

env:
  global:
    - CC_TEST_REPORTER_ID=808ac5a7a22827ca94cd442e9a0cbc2a8b5ba51c70633ed2ba870aa209a73616

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

scripts:
  # - bundle exec rspec spec
  - bundle exec rspec && CODECLIMATE_REPO_TOKEN=808ac5a7a22827ca94cd442e9a0cbc2a8b5ba51c70633ed2ba870aa209a73616

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT